version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: capital.scalable:spring-auto-restdocs-core
    versions:
    - 2.0.10
    - 2.0.9
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.asciidoctor:asciidoctor-maven-plugin
    versions:
    - 2.1.0
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - 1.3.2
  - dependency-name: org.junit.platform:junit-platform-engine
    versions:
    - 1.3.2
  - dependency-name: org.junit.platform:junit-platform-surefire-provider
    versions:
    - 1.3.2
